"""Add deletion_requested column to Task

Revision ID: f0f95e548b0d
Revises: 838b62ffd4c5
Create Date: 2025-09-02 19:19:22.804256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0f95e548b0d'
down_revision = '838b62ffd4c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deletion_requested', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('deletion_requested')

    # ### end Alembic commands ###
